//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveKiosk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descriptions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Descriptions()
        {
            this.Attraction = new HashSet<Attraction>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<byte> HoldingCapacity { get; set; }
        public Nullable<short> PermissibleLoad { get; set; }
        public int AgeGroup_ID { get; set; }
        public Nullable<System.TimeSpan> WorkingHours_1 { get; set; }
        public Nullable<System.TimeSpan> WorkingHours_2 { get; set; }
        public int Location_ID { get; set; }
        public int Developer_ID { get; set; }
        public Nullable<System.DateTime> DateOfCreation { get; set; }
        public string Support { get; set; }
    
        public virtual AgeGroup AgeGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attraction> Attraction { get; set; }
        public virtual Developer Developer { get; set; }
        public virtual Location Location { get; set; }
    }
}
